import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";

import { IBM_Plex_Mono } from "@next/font/google";
import Footer from "@/components/Footer";
import TabNav from "@/components/TabNav";
import Header from "@/components/Header";

const IbmPlexMono = IBM_Plex_Mono({
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "STEM Employee Database",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={IbmPlexMono.className}>
      <body className="font-mono antialiased min-h-screen gradient-retro overflow-hidden flex text-white">
        <div className="flex-1 flex flex-col uppercase">
          <Header />
          <main className="page-scroll-container">{children}</main>
          <Footer />
        </div>
        <TabNav />
        <Analytics />
      </body>
    </html>
  );
}
