import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";

import { IBM_Plex_Mono } from "@next/font/google";

const IbmPlexMono = IBM_Plex_Mono({
  weight: ["400", "500"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={IbmPlexMono.className}>
      <body className="font-mono antialiased">
        {children}
        <footer className="text-white text-center circular bg-blue pb-4 mt-4 w-full fixed bottom-0 overflow-x-clip">
          <div>
            <a className="text-white" href="/">
              go home
            </a>
          </div>
          <small className="text-xs">
            © 2024 by James Graham. All Rights Reserved.
          </small>
        </footer>
        <Analytics />
      </body>
    </html>
  );
}
